from langchain.tools.render import format_tool_to_openai_function
from langchain.agents import tool
from pydantic import BaseModel, Field


class retrieve_data_from_db(BaseModel):
    sql_query: str = Field(
        description="Here goes the MySQL query generated by LLM based on the users prompt by identifying the parameters"
    )


@tool(args_schema=retrieve_data_from_db)
def sql_data_retriever(sql_query):
    """This tool will take in a sql query and return the data"""
    return sql_query


db_data_retriever = format_tool_to_openai_function(sql_data_retriever)

print(db_data_retriever)


